name: beachfront-public-dependencies
channels:
  - default
  - conda-forge
  - bioconda
  - local
dependencies:
  - beautifulsoup4=4.6.0
  - blas=1.1=openblas
  - ca-certificates=2018.4.16
  - certifi=2018.4.16
  - chardet=3.0.4
  - click=6.6
  - cloog=0.18.0
  - conda-build=3.0.6
  - conda-verify=2.0.0
  - contextlib2=0.5.5
  - coverage=4.2
  - curl=7.60.0
  - cython=0.28.3
  - decorator=4.0.10
  - dill=0.2.5
  - expat=2.1.0
  - filelock=3.0.4
  - flask=0.11.1
  - flask-wtf=0.12
  - freexl=1.0.5
  - funcsigs=1.0.2
  - futures=3.2.0
  - gcc=4.8.5
  - gdal=2.1.3
  - geos=3.5.1
  - geos=3.6.2
  - geotiff=1.4.1
  - giflib=5.1.4
  - glob2=0.4.1
  - gmp=6.1.2
  - gunicorn=19.6.0
  - hdf4=4.2.12
  - hdf4=4.2.13
  - hdf5=1.10.1
  - hdf5=1.8.17
  - icu=58.2
  - isl=0.12.2
  - itsdangerous=0.24
  - jinja2=2.8
  - jpeg=9b
  - json-c=0.13.1
  - kealib=1.4.6
  - kealib=1.4.7
  - krb5=1.14.6
  - libdap4=3.18.3
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgdal=2.1.0
  - libgfortran=3.0.0
  - libiconv=1.15
  - libnetcdf=4.4.1
  - libnetcdf=4.4.1.1
  - libpng=1.6.28
  - libpq=9.6.3
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - markupsafe=0.23
  - mock=2.0.0
  - mpc=1.1.0
  - mpfr=3.1.5
  - ncurses=5.9
  - nose=1.3.7
  - numpy=1.14.0=py27_blas_openblas_200
  - openblas=0.2.20
  - openjpeg=2.1.2
  - openssl=1.0.2o
  - patchelf=0.9.2
  - pbr=4.0.4
  - pcre=8.41
  - phonenumbers=7.2.4
  - pip=9.0.3
  - pkginfo=1.4.2
  - proj4=4.9.2
  - proj4=4.9.3
  - pyproj=1.9.5.1
  - python=2.7.13
  - pyyaml=3.12
  - readline=6.2
  - readline=7.0
  - requests=2.13.0
  - setuptools=39.2.0
  - six=1.10.0
  - sqlite=3.13.0
  - sqlite=3.20.1
  - tk=8.5.19
  - tk=8.6.7
  - toolchain=2.1.5
  - util-linux=2.21
  - werkzeug=0.11.10
  - wheel=0.29.0
  - wheel=0.31.0
  - wtforms=2.1
  - wtforms-components=0.10.0
  - xerces-c=3.1.4
  - xerces-c=3.2.0
  - xz=5.2.3
  - zlib=1.2.11=h470a237_3
